channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.0.1
- pip:
  - mlflow==2.22.0
  - attrs==24.3.0
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - google-cloud-storage==3.1.0
  - ipython==8.30.0
  - jaraco-text==3.12.1
  - matplotlib==3.10.0
  - pandas==2.2.3
  - psutil==5.9.0
  - scikeras==0.13.0
  - scikit-learn==1.4.2
  - tensorflow==2.16.1
name: mlflow-env
